### ISSUE TITLE
vsphere read-only user does not work

### ISSUE THREAD

**Issue by is4it-lab** [evoila/collectsphere#22] opened 2017-03-14 08:27 UTC
Hi,

when I configured a read-only user in vsphere for the monitoring, I'll get a error message from python script
collectd[10786]: Unhandled python exception in init callback: vim.fault.NoPermission: (vim.fault.NoPermission) {#012   dynamicType = <unset>,#012   dynamicProperty = (vmodl.DynamicProperty) [],#012   msg = 'Permission to perform this operation was denied.',#012   faultCause = <unset>,#012   faultMessage = (vmodl.LocalizableMessage) [],#012   object = 'vim.Folder:group-d1',#012   privilegeId = 'Performance.ModifyIntervals'#012}

the same user works fine with administrator rights. It would be fine to use an account with read-only permissions.

Another issue are the counters. Is the an overview available what types of counters are available and what they means ? 
at some points there areonly read values but no write (eg. HostSystem-Datastore-average-read - but no write counter ...)

best regards
robert

**Comment by jakape** [comment] 2017-03-20 10:33
Hi there,

 A ESX/Vsphere user with `System.View` and `Performance.ModifyIntervals` privileges.

I think, the counters are all listed within the [vmware-types.db](https://github.com/evoila/collectsphere/blob/master/vmware-types.db). Beware that you might fail the collectd-plugin when you try to collect values that are not present on all devices.

I have already updated the `README.md` and filed a pull request, but unfortunately @dennis1987 did not yet merged it.

Cheers,
Jan

**Comment by is4it-lab** [comment] 2017-03-21 12:33
Hi,

thanks a lot. 
The vsphere user with Performance.ModifyIntervals privileges works fine.

concerning the counters I'm a little bit confused. vmware-types.db is a good hint, but how to get them catched all ? (or a subset of them)
When using no keywords for Host_Counters and VM_Counters in the config file I'll get a lot of them, but many are missing. For example the complete mem section.
Using cpu.usage or mem.usage or net.usage works fine for each alone. When putting them together in on line the mem counters are missing again.
It gets stranger wen using disk.usage. Then I'll get a subset of the counters again - for example read is present while write is missing. I've tried a workarround with sepereate Module sections in the config file  for CPU, Mem, Net..
but what are the right keywords ? <xxx>.usage looks like delivering only summary values. 

any ideas ?

best regards.
robert

**Comment by jakape** [comment] 2017-03-21 13:12
Well, I had mixed results in my setup recently, but in theory you can define `all` and it should just do what you want. The issue with the `mem` section I noticed as well but I thought that it was an issue in the communication between the python module and collectd itself. The issue in question is described in detail within [this stackoverflow question](https://stackoverflow.com/questions/41870270/influxdb-collectd-parse-error-invalid-data-service-collectd), that obviously has had no replies up until now.

Since I've had no time to investigate this issue further, we have removed collectd entirely from the equation and use a [standalone software](https://github.com/Oxalide/vsphere-influxdb-go) that directly writes to influxdb (and not to its collectd-interface). But again, I believe the issue is not with the collectd-interface from influxdb but in the communication/callback with/from python modules.

Cheers,
Jan

Edit: Just as a follow-up question, @is4it-lab, do you use influxdb for reading/consuming the data or do you use something else?

**Comment by dennis1987** [comment] 2017-03-27 09:45
Hi there,

I cannot reproduce the issue...
I've committed a patch 10 days ago [0caa609](https://github.com/evoila/collectsphere/commit/0caa609a1073d6266ddf910b1164dfe5bf8e5d21). This is also included in the actual release (v1.1.1). 
The release v1.1.0 (and all between Feb. 17 and Mar 17.) is broken. 

Best regards,
Dennis

**Comment by dennis1987** [comment] 2017-03-29 08:31
![](https://github.trello.services/images/mini-trello-icon.png) [b](https://trello.com/c/kEAmvSne/2-b)

**Closed as completed** 2017-04-10 13:47 UTC
